package model;
// Generated Feb 22, 2017 12:01:35 AM by Hibernate Tools 4.3.1

import java.sql.Timestamp;
import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments implements java.io.Serializable {

    private Integer idComment;
    private Posts posts;
    private Users users;
    private String content;
    private String status;
    private Timestamp commentDate;

    public Comments() {
    }


    public Comments(Posts posts, Users users, String content, String status, Timestamp commentDate) {
        this.posts = posts;
        this.users = users;
        this.content = content;
        this.commentDate = commentDate;
        this.status = status;
    }

    public Integer getIdComment() {
        return this.idComment;
    }
    
    
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void setIdComment(Integer idComment) {
        this.idComment = idComment;
    }

    public Posts getPosts() {
        return this.posts;
    }

    public void setPosts(Posts posts) {
        this.posts = posts;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Date getCommentDate() {
        return this.commentDate;
    }

    public void setCommentDate(Timestamp commentDate) {
        this.commentDate = commentDate;
    }

}
