package model;
// Generated Feb 22, 2017 12:01:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Posts generated by hbm2java
 */
public class Posts  implements java.io.Serializable {


     private Integer idPost;
     private Users users;
     private String title;
     private String content;
     private String postType;
     private Date postDate;
     private Set<Comments> commentses = new HashSet<Comments>(0);
     private Set<Votes> voteses = new HashSet<Votes>(0);

    public Posts() {
    }

	
    public Posts(Users users, String title, String content, String postType, Date postDate) {
        this.users = users;
        this.title = title;
        this.content = content;
        this.postType = postType;
        this.postDate = postDate;
    }
    public Posts(Users users, String title, String content, String postType, Date postDate, Set<Comments> commentses, Set<Votes> voteses) {
       this.users = users;
       this.title = title;
       this.content = content;
       this.postType = postType;
       this.postDate = postDate;
       this.commentses = commentses;
       this.voteses = voteses;
    }
   
    public Integer getIdPost() {
        return this.idPost;
    }
    
    public void setIdPost(Integer idPost) {
        this.idPost = idPost;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getPostType() {
        return this.postType;
    }
    
    public void setPostType(String postType) {
        this.postType = postType;
    }
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }
    public Set<Comments> getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set<Comments> commentses) {
        this.commentses = commentses;
    }
    public Set<Votes> getVoteses() {
        return this.voteses;
    }
    
    public void setVoteses(Set<Votes> voteses) {
        this.voteses = voteses;
    }




}


