package model;
// Generated Feb 22, 2017 12:01:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer idUser;
     private String username;
     private String password;
     private String name;
     private int age;
     private String email;
     private String gender;
     private String type;
     private String photolink;
     private Set<Votes> voteses = new HashSet<Votes>(0);
     private Set<Comments> commentses = new HashSet<Comments>(0);
     private Set<Posts> postses = new HashSet<Posts>(0);

    public Users() {
    }

	
    public Users(String username, String password, String name, int age, String email, String gender, String type, String photolink) {
        this.username = username;
        this.password = password;
        this.name = name;
        this.age = age;
        this.email = email;
        this.gender = gender;
        this.type = type;
        this.photolink = photolink;
    }
    public Users(String username, String password, String name, int age, String email, String gender, String type, String photolink, Set<Votes> voteses, Set<Comments> commentses, Set<Posts> postses) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.age = age;
       this.email = email;
       this.gender = gender;
       this.type = type;
       this.photolink = photolink;
       this.voteses = voteses;
       this.commentses = commentses;
       this.postses = postses;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getPhotolink() {
        return this.photolink;
    }
    
    public void setPhotolink(String photolink) {
        this.photolink = photolink;
    }
    public Set<Votes> getVoteses() {
        return this.voteses;
    }
    
    public void setVoteses(Set<Votes> voteses) {
        this.voteses = voteses;
    }
    public Set<Comments> getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set<Comments> commentses) {
        this.commentses = commentses;
    }
    public Set<Posts> getPostses() {
        return this.postses;
    }
    
    public void setPostses(Set<Posts> postses) {
        this.postses = postses;
    }




}


