package model;
// Generated Feb 22, 2017 12:01:35 AM by Hibernate Tools 4.3.1



/**
 * Votes generated by hbm2java
 */
public class Votes  implements java.io.Serializable {


     private Integer idVote;
     private Posts posts;
     private Users users;
     private Comments comments;
     private int vote;

    public Votes() {
    }

    public Votes(Posts posts, Users users, Comments idComment, int vote) {
       this.posts = posts;
       this.users = users;
       this.comments = idComment;
       this.vote = vote;
    }
   
    public Integer getIdVote() {
        return this.idVote;
    }
    
    public void setIdVote(Integer idVote) {
        this.idVote = idVote;
    }
    public Posts getPosts() {
        return this.posts;
    }
    
    public void setPosts(Posts posts) {
        this.posts = posts;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Comments getComments() {
        return this.comments;
    }
    
    public void setComments(Comments comments) {
        this.comments = comments;
    }
    public int getVote() {
        return this.vote;
    }
    
    public void setVote(int vote) {
        this.vote = vote;
    }




}


